"""raw_doc_type em documents

Revision ID: 752ce40a44a0
Revises: 9b813a6e8805
Create Date: 2026-07-26 17:17:40.595755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '752ce40a44a0'
down_revision: Union[str, Sequence[str], None] = '9b813a6e8805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_doc_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_doc_type')
    # ### end Alembic commands ###
